### ISSUE TITLE
catch_api.json inaccessible

### ISSUE THREAD

**Issue by arthurian** [nmaekawa/catchpy#1]
@nmaekawa Just a heads up that I'm getting a permission denied error when I try to access https://catchpy.harvardx.harvard.edu.s3.amazonaws.com/api/catch_api.json:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>...</RequestId>
  <HostId>...</HostId>
</Error>
```

Also, would it make sense to host **catch_api.json** and **catch_context_jsonld.json** in this git repository rather than in a separate S3 bucket?

**Comment by nmaekawa** [comment]
you can find the swagger api and jsonld in the anno/static/anno dir. i'll remove this from readme because it's not working as i intended to...

**Comment by nmaekawa** [comment]
s3 reference removed.
